### ISSUE TITLE
Manual call of updatePrice if 'scheduleInSec > 0'

### ISSUE THREAD

**Issue by astroseger** [ksridharbabuus/PricingOracles-Contracts#1]
There is a following situation: we have scheduleInSec > 0, so __callback is called automatically each  scheduleInSec seconds. 

And now for some reason we want to update price one time manually.

What will happen if we simply call updatePrice without calling updateSchedule (and setting scheduleInSec in 0)? I believe it will start updating prices each scheduleInSec/2. 

It seems we should add the following condition to updatePrice (in order to forbid calling updatePrice manually if scheduleInSec > 0)
```
if((msg.sender == owner && scheduleInSec > 0) )) revert(); 
```

**Comment by astroseger** [comment]
@ksridharbabuus After reading oraclize.it documentation I'm pretty sure there is a bug..
I think solution might be as following:
We should have two separate function:
 -- ```oraclizePleaseUpdatePrice``` -- for update price right away single time. 
-- ```oraclizePleaseSheduleNextUpdatePrice``` --- for schedule next update price in  scheduleInSec seconds

We also should prevent situation in which updateSchedule is called between oraclizePleaseUpdatePrice and __callback.

```solidity
function updateSchedule(uint256 _frequencyInSec) public {
       require(msg.sender == owner);

       // we prevent the nasty bug then updateSchedule is called between oraclizePleaseUpdatePrice and __callback
       require (scheduleInSec >= 0); 
       scheduleInSec = _frequencyInSec;
       emit NewSchedule(_frequencyInSec);
   }

 function __callback(bytes32 myid, string memory result) public {
       if (msg.sender != oraclize_cbAddress()) revert();
       AGIPrice = result;

       emit PriceUpdated(result);

       if(scheduleInSec > 0) {
            oraclizePleaseSheduleNextUpdatePrice();
        }
       //remove safeguard
       if (scheduleInSec < 0){
       scheduleInSec = 0
       }
   }

   function oraclizePleaseSheduleNextUpdatePrice() public {
       require(scheduleInSec > 0);
       require(msg.sender == owner || msg.sender == oraclize_cbAddress())

       if (oraclize_getPrice("URL") > address(this).balance) {
           emit NewOraclizeQuery("Oraclize query was NOT sent, not enough fee");
       } 
        else {
           emit NewOraclizeQuery("Schedule next oraclize quire in scheduleInSec seconds");
           oraclize_query(scheduleInSec, "URL", sURL);
           }
   }
 function oraclizePleaseUpdatePrice() public {
       require(msg.sender == owner)
       require(scheduleInSec == 0)
       if (oraclize_getPrice("URL") > address(this).balance) {

           emit NewOraclizeQuery("Oraclize query was NOT sent, not enough fee");

       } else {
           
            // we will not be able to run updateSchedule before __callback is called
            scheduleInSec = -1;
           emit NewOraclizeQuery("Oraclize query was sent, standing by for the answer..");
           oraclize_query("URL", sURL);
       }
   }

```

**Comment by ksridharbabuus** [comment]
Right now we have not considered the manual call for the update Price. Will add that logic where we enable manual call without impacting the Schedule call.

**Comment by ksridharbabuus** [comment]
@astroseger I am thinking We should be able to handle the logic with a forcibleExecutionFlag. Let me give try than creating separate functions.

**Comment by ksridharbabuus** [comment]
@astroseger Updated the code with a flag to the method to check for force / manual execution. Went with the logic support multiple manual requests without impacting the current running schedule.

Not able to test as there seems to some issue with the Ropsten Oraclize queries. Hope it will be fixed soon.

**Comment by ksridharbabuus** [comment]
@astroseger Updated the logic to have manual/forcible calls during the schedule with no impact to the current schedule by adding flag to the function call and mapping field to store forcible query Ids.

Tested in Ropsten @ https://ropsten.etherscan.io/address/0x7438104980916ab40ecdf80bfd0a2804c229500e 
Block#4734635 - Scheduled Execution (in 15 Mins)
Block# 4734643, 4734646 - Force Request
Block# 4734657, 4734658 - Force Request
Block# 4734713 - Scheduled Execution (in 15 Mins)

Please have a look and let me know your comments. Thanks!

**Comment by ksridharbabuus** [comment]
@astroseger we can also check the status of the query in oraclize app, we can get the queryId from the events:

http://app.oraclize.it/home/check_query

**Comment by ksridharbabuus** [comment]
@astroseger Can you please complete the review as we can deploy this piece in Kovan network.

**Comment by astroseger** [comment]
@ksridharbabuus 

I.
What will happen if your run second ```queryId = oraclize_query(scheduleInSec, "URL", sURL);```  in case then the first one hasn't been yet executed? Am I right that it will schedule the second oraclized call?

If it is true than there is a problem (not very big though). If user call ```requestForUpdatePrice(false)``` in case then scheduled execution is already initialized then price will be updated two times each scheduleInSec. In the current design it can be easily stopped by setting scheduleInSec to 0, so it is not a very big issue.

But maybe we could have a flag which indicate that scheduled execution is already initialized and forbid to call ```requestForUpdatePrice(false)``` second time.

II.
I guess you don't need to call ```delete forcibleQueryIds[myid];``` if queryIds are not duplicated.

**Comment by ksridharbabuus** [comment]
@astroseger 
I. You are absolutely right with the current logic implementation. Intentionally allowing to call again as we dont have the control over the oracle execution. In case if there are any issue we should be able to force it again. I hope it should be fine as we can reset by scheduling freq to zero.
II. Deleting it just to make sure not to add it up to storage as we don't need these values after execution. We can get the QueryId from the events as well.

Thanks a lot  for all your comments. Will go ahead and release it to Kovan Network and schedule it to run once in a day.

**Comment by ksridharbabuus** [comment]
Closing this issue. Thanks for your review @astroseger
