### ISSUE TITLE
rename updatePrice?

### ISSUE THREAD

**Issue by astroseger** [ksridharbabuus/PricingOracles-Contracts#2]
Function updatePrice do not update price. It only ask oraclize to do it... Maybe we could call it askForUpdatePrice or oraclizeUpdatePrice or oraclizeCouldYouPleaseUpdatePrice or something like this :) .

**Comment by ksridharbabuus** [comment]
Sure will do it accordingly.

**Comment by ksridharbabuus** [comment]
Changed the function name and also added bool parameter to check for manual execution.
